export const SET_AVAILABLE_FOR_WORK = 'SET_AVAILABLE_FOR_WORK';

export const SET_AUTORIZED_USER = 'SET_AUTORIZED_USER';

export const SET_THEME = 'SET_THEME';

export const USER_DATA_REQUEST = 'USER_DATA_REQUEST';
export const USER_DATA_RESPONSE = 'USER_DATA_RESPONSE';
