export const SET_AVAILABLE_FOR_WORK = 'SET_AVAILABLE_FOR_WORK';

export const SET_AUTORIZED_USER = 'SET_AUTORIZED_USER';

export const SET_THEME = 'SET_THEME';

export const USER_DATA_REQUEST = 'USER_DATA_REQUEST';
export const USER_DATA_RESPONSE = 'USER_DATA_RESPONSE';
export const USER_DATA_FAILED = 'USER_DATA_FAILED';

export const USER_SHOTS_REQUEST = 'USER_SHOTS_REQUEST';
export const USER_SHOTS_RESPONSE = 'USER_SHOTS_RESPONSE';
export const USER_SHOTS_FAILED = 'USER_SHOTS_FAILED';

export const USER_SHOT_REQUEST = 'USER_SHOT_REQUEST';
export const USER_SHOT_RESPONSE = 'USER_SHOT_RESPONSE';
export const USER_SHOT_FAILED = 'USER_SHOT_FAILED';

export const OPEN_SHOT_MODAL = 'OPEN_SHOT_MODAL';
export const CLOSE_SHOT_MODAL = 'CLOSE_SHOT_MODAL';
